# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: .Net Build
        # You may pin to the exact commit or the version.
        # uses: EasyDesk/action-dotnet-build@d2c47d8701e3ea8db03dcabaacb37204fe123a22
        uses: EasyDesk/action-dotnet-build@v1.0.0
        with:  
          # Additional build arguments to pass to 'dotnet build'.
          #build-args: # optional
          # The build configuration to use (defaults to 'Release').
          #build-configuration: # optional, default is Release
          # The path to the project or solution to build (defaults to the current directory).
          path: Telepathy.sln # optional, default is .
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: Telapathy # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: Telepathy\bin\Release\
          # The desired behavior if no files are found using the provided path.
      
      
